/**
 * 新闻 36 / 命运 37 / 魔法屋 12 条件 × 12 效果的语义说明（入库；D2 第二部分，docs/research/events-from-exe.md 的来源）。
 * 全部是本项目对 v3.11 反汇编的自拟概括（summary ≤ 15 字，不照抄原文），数值一律来自 anchors/constants.json 在两版 exe 上的读取结果。
 * params：参数名 → 常量锚点 id；pi = 该金额乘物价指数。
 * notes：与 docs/research/r_squares_events.md、design/engine.md §10.6–§10.8 不一致或需要特别说明之处。
 */

export interface ParamRef {
  name: string;
  const: string;
  /** 金额 × 物价指数 */
  pi?: boolean;
  unit?: string;
}

export interface EventSpec {
  id: number;
  summary: string;
  /** 引擎效果键（design/engine.md §10.6–§10.8 的 effect.k；新增的以 * 标出） */
  effect: string;
  /** 目标选择方式 */
  target: string;
  /** 可行条件（不满足时新闻/命运跳过，游标照样前进） */
  feasible: string;
  params: ParamRef[];
  notes?: string[];
}

const p = (name: string, id: string, extra: Partial<ParamRef> = {}): ParamRef => ({ name, const: id, ...extra });

// ───────────────────────── 新闻 ─────────────────────────

/** 新闻分类号 0..5 的自拟称呼（原版分类名只在 .cache 的抽取结果里） */
export const NEWS_CATEGORY_LABELS: readonly string[] = ['奇闻', '政府公告', '社会', '路况', '气象', '财经'];

export const NEWS_SPEC: readonly EventSpec[] = [
  {
    id: 0,
    summary: '在押玩家全部获释',
    effect: 'releaseAll',
    target: '全体在押玩家',
    feasible: '有玩家在押',
    params: [],
  },
  {
    id: 1,
    summary: '在押者刑期再加几天',
    effect: 'extendAll',
    target: '全体在押玩家',
    feasible: '有玩家在押',
    params: [p('days', 'news.1.days', { unit: '天' })],
    notes: ['天数加在关押计数字节上后 & 0x7f'],
  },
  {
    id: 2,
    summary: '住院玩家全部出院',
    effect: 'releaseAll',
    target: '全体住院玩家',
    feasible: '有玩家住院',
    params: [],
  },
  {
    id: 3,
    summary: '住院者再多住几天',
    effect: 'extendAll',
    target: '全体住院玩家',
    feasible: '有玩家住院',
    params: [p('days', 'news.3.days', { unit: '天' })],
  },
  {
    id: 4,
    summary: '外星人来袭范围破坏',
    effect: 'alienAttack',
    target: '随机一处有建筑的住宅或设施为中心（rand % 候选数）',
    feasible: '有等级 > 0 的住宅或设施',
    params: [
      p('halfWidth', 'news.4.halfWidth', { unit: '像素' }),
      p('hospitalDays', 'news.4.hospitalDays', { unit: '天' }),
    ],
    notes: ['范围伤害模式 1（与核弹同一函数），范围内玩家住院；不记敌意（施放者 -1）'],
  },
  {
    id: 5,
    summary: '怪兽摧毁一处建筑',
    effect: 'monster',
    target: '随机一处有建筑的住宅或设施',
    feasible: '有等级 > 0 的住宅或设施',
    params: [],
    notes: ['地块损坏模式 1：清建筑且清地主（与山洪相同）'],
  },
  {
    id: 6,
    summary: '某路段地价上调三成',
    effect: 'streetPrice',
    target: '随机任一住宅或设施（rand % (住宅数 + 设施数)）',
    feasible: '恒可',
    params: [p('factor', 'news.6.factor'), p('factorFacility', 'news.6.factorFacility')],
    notes: ['住宅：同名路段每块地价 × 1.3 后截断存回 16 位；设施只改这一处'],
  },
  {
    id: 7,
    summary: '无主地产公开拍卖',
    effect: 'publicAuction',
    target: '随机一处无主住宅或设施',
    feasible: '有无主的住宅或设施',
    params: [],
    notes: ['拍卖卖方为 -1（无卖方）'],
  },
  {
    id: 8,
    summary: '表扬地产最多的人',
    effect: 'rewardTopLandlord',
    target: '住宅 + 设施块数最多者（严格大于才替换：并列取座位号最小）',
    feasible: '有人拥有住宅或设施',
    params: [p('reward', 'news.8.rewardPI', { pi: true, unit: '元' })],
    notes: ['奖金进现金'],
  },
  {
    id: 9,
    summary: '补助地产最少的人',
    effect: 'subsidyFewest',
    target: '在场玩家中住宅 + 设施块数最少者（初值 10000，严格小于才替换：并列取座位号最小）',
    feasible: '有人拥有住宅或设施',
    params: [p('subsidy', 'news.9.subsidyPI', { pi: true, unit: '元' })],
    notes: [
      '与 r_squares_events #9、engine.md §10.6 不一致：exe 不排除 0 块地的玩家，并列时取座位号最小者（文档写「有地者」「并列取最后一个」）',
    ],
  },
  {
    id: 10,
    summary: '表扬持股最多的人',
    effect: 'rewardTopShareholder',
    target: '12 支股票持股总数最多者（并列取座位号最小）',
    feasible: '有人持股',
    params: [p('reward', 'news.10.rewardPI', { pi: true, unit: '元' })],
  },
  {
    id: 11,
    summary: '全员缴所得税',
    effect: 'incomeTax',
    target: '全体在场玩家',
    feasible: '恒可',
    params: [p('rate', 'news.11.rate')],
    notes: ['税额 = trunc(现金 × 0.05)，不乘物价指数，进公库；全局标志 0x46caf8 非 0 时整段不扣（语义未明）'],
  },
  {
    id: 12,
    summary: '全员缴地价税',
    effect: 'landTax',
    target: '全体在场玩家',
    feasible: '有人拥有住宅或设施',
    params: [p('rate', 'news.12.rate')],
    notes: [
      '税额 = trunc(Σ(住宅 地价 + 等级 × 房价) + Σ(设施 地价 + 等级 × +0x24 费率)) × 0.05) × 物价指数；engine.md 只写了住宅部分',
    ],
  },
  {
    id: 13,
    summary: '全员缴证交税',
    effect: 'stockTax',
    target: '全体在场玩家',
    feasible: '有人持股',
    params: [p('rate', 'news.13.rate')],
    notes: ['税额 = trunc(Σ 持股 × 现价(f32) × 0.05) × 物价指数'],
  },
  {
    id: 14,
    summary: '某路段地价下跌三成',
    effect: 'streetPrice',
    target: '随机任一住宅或设施',
    feasible: '恒可',
    params: [p('factor', 'news.14.factor')],
  },
  {
    id: 15,
    summary: '民宅瓦斯爆炸失火',
    effect: 'gasExplosion',
    target: '随机一处有建筑的住宅（只在住宅中抽）',
    feasible: '有等级 > 0 的住宅或设施（与 4、5 共用判定）',
    params: [],
    notes: [
      '地块损坏模式 0（拆建筑、保留地主）',
      '原版瑕疵：可行性把设施也算进去，但处理函数只在住宅中抽；只有设施有建筑时会除以 0',
    ],
  },
  {
    id: 16,
    summary: '豪雨步行者停一回合',
    effect: 'stayByVehicle',
    target: '座驾 = 步行的在场玩家',
    feasible: '有步行玩家',
    params: [],
    notes: ['写停留标志 = 1'],
  },
  {
    id: 17,
    summary: '塞车乘车者停一回合',
    effect: 'stayByVehicle',
    target: '座驾 ≠ 步行（机车、汽车）的在场玩家',
    feasible: '有乘车玩家',
    params: [],
  },
  {
    id: 18,
    summary: '强震路段房屋倒塌',
    effect: 'earthquake',
    target: '随机任一住宅或设施',
    feasible: '恒可',
    params: [],
    notes: ['住宅：同名路段每块等级 −1，带 +0x18 标记的直接清为空地；设施：等级 −1，到 0 清设施种类'],
  },
  {
    id: 19,
    summary: '山洪冲走一块地',
    effect: 'flood',
    target: '随机任一住宅或设施',
    feasible: '恒可',
    params: [],
    notes: ['地块损坏模式 1：清建筑且清地主'],
  },
  {
    id: 20,
    summary: '台风范围损坏房屋',
    effect: 'typhoon',
    target: '随机任一住宅或设施为中心',
    feasible: '恒可',
    params: [p('halfWidth', 'news.20.halfWidth', { unit: '像素' })],
    notes: ['范围伤害模式 0，不伤人'],
  },
  {
    id: 21,
    summary: '龙卷风毁一栋房',
    effect: 'tornado',
    target: '随机任一住宅或设施',
    feasible: '恒可',
    params: [],
    notes: ['地块损坏模式 0'],
  },
  {
    id: 22,
    summary: '银行挤兑暂停放款',
    effect: 'bankRun',
    target: '全体在场玩家（各自的计数）',
    feasible: '恒可',
    params: [p('days', 'news.22.days', { unit: '天' })],
  },
  {
    id: 23,
    summary: '无贷款者得储金红利',
    effect: 'bonusInterest',
    target: '贷款 = 0 的在场玩家',
    feasible: '恒可',
    params: [p('rate', 'news.23.rate')],
    notes: ['红利 = trunc(存款 × 0.1)，进存款'],
  },
  {
    id: 24,
    summary: '股市全面崩盘',
    effect: 'marketAll',
    target: '12 支股票',
    feasible: '恒可',
    params: [p('trend', 'news.24.trend')],
    notes: ['趋势字节低半字节 = 下跌天数、高半字节 = 上涨天数；写入后立即重算股价'],
  },
  {
    id: 25,
    summary: '股市全面上涨',
    effect: 'marketAll',
    target: '12 支股票',
    feasible: '恒可',
    params: [p('trend', 'news.25.trend')],
  },
  {
    id: 26,
    summary: '股市暂停交易',
    effect: 'marketHalt',
    target: '全局',
    feasible: '恒可',
    params: [p('days', 'news.26.days', { unit: '天' })],
  },
  {
    id: 27,
    summary: '某支股票停牌',
    effect: 'suspend',
    target: '随机一支股票（rand % 12，可能重复抽到已停牌的）',
    feasible: '恒可',
    params: [p('pick', 'news.27.pick'), p('days', 'news.27.suspendDays', { unit: '天' })],
    notes: ['文案写 10 天，exe 写入 15'],
  },
  {
    id: 28,
    summary: '停牌股票恢复交易',
    effect: 'resume',
    target: '随机一支停牌股',
    feasible: '有停牌股',
    params: [],
  },
  {
    id: 29,
    summary: '超贷董事长坐牢',
    effect: 'overLoanJail',
    target: '随机一家有董事长的公司，其董事长',
    feasible: '有董事长在场且其受困类计数（玩家 +0x32..+0x35）全为 0',
    params: [p('days', 'news.29.jailDays', { unit: '天' })],
    notes: ['先过免罪卡 → 嫁祸卡判定（与魔法屋、命运相同的函数），不查神明加持'],
  },
  {
    id: 30,
    summary: '工厂污染被罚款',
    effect: 'companyFine',
    target: '随机任一公司（rand % 公司数，不要求有董事长）',
    feasible: '恒可',
    params: [p('fine', 'news.30.fine', { unit: '元' }), p('trend', 'news.30.trend')],
    notes: ['本月盈余与累计盈余同减；只在股票下标 < 12 时写趋势并重算股价'],
  },
  {
    id: 31,
    summary: '海外投资获利',
    effect: 'overseas',
    target: '随机任一公司',
    feasible: '恒可',
    params: [p('gain', 'news.31.gain', { unit: '元' }), p('trend', 'news.31.trend')],
  },
  {
    id: 32,
    summary: '海外投资亏损',
    effect: 'overseas',
    target: '随机任一公司',
    feasible: '恒可',
    params: [p('loss', 'news.32.loss', { unit: '元' }), p('trend', 'news.32.trend')],
  },
  {
    id: 33,
    summary: '违规开发山坡地罚款',
    effect: 'companyFine',
    target: '随机任一公司',
    feasible: '恒可',
    params: [p('fine', 'news.30.fine', { unit: '元' }), p('trend', 'news.30.trend')],
    notes: ['与 30 共用扣款代码'],
  },
  {
    id: 34,
    summary: '噪音公害罚款',
    effect: 'companyFine',
    target: '随机任一公司',
    feasible: '恒可',
    params: [p('fine', 'news.34.fine', { unit: '元' }), p('trend', 'news.30.trend')],
  },
  {
    id: 35,
    summary: '公司获利翻倍',
    effect: 'doubleProfit',
    target: '随机一家本月盈余 > 10000 的公司',
    feasible: '有盈余 > 10000 的公司',
    params: [p('threshold', 'news.35.threshold', { unit: '元' }), p('divisor', 'news.35.divisor')],
    notes: [
      '本月盈余 × 2，累计盈余 + 2 × 原盈余；上涨天数 = (原盈余 / 10000) 写入高半字节（按字节截断，即对 16 取模），engine.md 的 min(15, …) 与此不同',
    ],
  },
];

// ───────────────────────── 命运 ─────────────────────────

export const FATE_SPEC: readonly EventSpec[] = [
  {
    id: 0,
    summary: '自家一栋房被强拆',
    effect: 'demolishOwn',
    target: '自己一块有建筑的住宅（随机）',
    feasible: '自己有等级 > 0 的住宅',
    params: [],
    notes: ['补偿 = 等级 × 房价进现金（不乘物价指数），等级与 +0x18 清零'],
  },
  {
    id: 1,
    summary: '自家空地被征收',
    effect: 'expropriate',
    target: '自己一块空地（随机）',
    feasible: '自己有等级 = 0 的住宅',
    params: [],
    notes: ['补偿 = 地价进现金，地主清空'],
  },
  {
    id: 2,
    summary: '人头被冒用贷款',
    effect: 'fakeLoan',
    target: '自己',
    feasible: '恒可',
    params: [p('loan', 'fate.2.loanPI', { pi: true, unit: '元' })],
    notes: ['贷款直接加上；没有到期日时设到期日；投保中由保险公司赔同额'],
  },
  {
    id: 3,
    summary: '跳票被银行拒往',
    effect: 'bankRefuse',
    target: '自己',
    feasible: '恒可',
    params: [p('days', 'fate.3.days', { unit: '天' })],
    notes: ['拒绝往来计数累加；罚金类加持只处理「免付」，不处理「加倍」'],
  },
  {
    id: 4,
    summary: '挪用他人一成存款',
    effect: 'embezzle',
    target: '其他有存款的在场玩家',
    feasible: '恒可',
    params: [p('pct', 'fate.4.pct', { unit: '%' })],
    notes: ['每人 trunc(存款 × 10 / 100.0) 从其存款转入自己的存款'],
  },
  {
    id: 5,
    summary: '生日向每人要张卡',
    effect: 'birthday',
    target: '其他有卡的在场玩家',
    feasible: '有对手持卡',
    params: [],
    notes: ['真人逐人挑卡；电脑随机取'],
  },
  {
    id: 6,
    summary: '被迫出国观光',
    effect: 'abroad',
    target: '自己（免罪 → 嫁祸判定后的最终目标）',
    feasible: '恒可',
    params: [p('days', 'fate.6.days', { unit: '天' })],
  },
  {
    id: 7,
    summary: '被外星人绑走',
    effect: 'abroad',
    target: '自己（免罪 → 嫁祸判定后的最终目标）',
    feasible: '恒可',
    params: [p('days', 'fate.7.days', { unit: '天' })],
  },
  {
    id: 8,
    summary: '违约交割损一成股',
    effect: 'stockDefault',
    target: '自己',
    feasible: '自己持股',
    params: [p('pct', 'fate.8.pct', { unit: '%' })],
    notes: ['每支 trunc(持股 × 10 / 100.0) 股收回；罚金类加持只处理「免付」'],
  },
  {
    id: 9,
    summary: '股票全部变卖求现',
    effect: 'sellAllStocks',
    target: '自己',
    feasible: '自己持股',
    params: [],
    notes: ['罚金类加持只处理「免付」'],
  },
  {
    id: 10,
    summary: '机车被偷',
    effect: 'loseVehicle',
    target: '自己',
    feasible: '骑机车；开汽车时改为 11；步行时跳过',
    params: [],
    notes: ['劫难类加持只处理「逃过」'],
  },
  {
    id: 11,
    summary: '汽车撞毁',
    effect: 'loseVehicle',
    target: '自己',
    feasible: '开汽车；骑机车时改为 10；步行时跳过',
    params: [],
  },
  {
    id: 12,
    summary: '掉进水沟就医',
    effect: 'ditch',
    target: '自己（免罪 → 嫁祸后的最终目标）',
    feasible: '步行；骑机车时改为 13；开汽车时跳过',
    params: [p('days', 'fate.12.days', { unit: '天' })],
    notes: ['先毁座驾再住院'],
  },
  {
    id: 13,
    summary: '骑车摔伤住院',
    effect: 'ditch',
    target: '自己（免罪 → 嫁祸后的最终目标）',
    feasible: '骑机车；步行时改为 12；开汽车时跳过',
    params: [p('days', 'fate.13.days', { unit: '天' })],
  },
  {
    id: 14,
    summary: '行人闯红灯罚款',
    effect: 'fine',
    target: '自己',
    feasible: '步行；机车改 15、汽车改 16',
    params: [p('amount', 'fate.14.amountPI', { pi: true, unit: '元' })],
    notes: ['罚金进公库；投保中由保险公司赔同额'],
  },
  {
    id: 15,
    summary: '骑车没戴安全帽',
    effect: 'fine',
    target: '自己',
    feasible: '骑机车；步行改 14、汽车改 16',
    params: [p('amount', 'fate.15.amountPI', { pi: true, unit: '元' })],
    notes: ['处理函数里若发现在步行，改走 12 的流程（替换规则已先挡掉）'],
  },
  {
    id: 16,
    summary: '开车超速罚款',
    effect: 'fine',
    target: '自己',
    feasible: '开汽车；步行改 14、机车改 15',
    params: [p('amount', 'fate.16.amountPI', { pi: true, unit: '元' })],
    notes: ['与 15 共用收尾代码，同样查罚金类加持（g_arbitration「汽车超速未接加持」与 exe 不符）'],
  },
  {
    id: 17,
    summary: '请全场吃大餐',
    effect: 'fine',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.17.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 18,
    summary: '乱丢垃圾罚款',
    effect: 'fine',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.18.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 19,
    summary: '小狗便溺罚款',
    effect: 'fine',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.19.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 20,
    summary: '路边捡到钱（小）',
    effect: 'reward',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.20.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 21,
    summary: '路边捡到钱（中）',
    effect: 'reward',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.21.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 22,
    summary: '路边捡到钱（大）',
    effect: 'reward',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.22.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 23,
    summary: '钱包遗失（小）',
    effect: 'fine',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.23.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 24,
    summary: '钱包遗失（大）',
    effect: 'fine',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.24.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 25,
    summary: '意外继承遗产',
    effect: 'reward',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.25.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 26,
    summary: '被倒会损失',
    effect: 'fine',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.26.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 27,
    summary: '发票中奖（小）',
    effect: 'reward',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.27.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 28,
    summary: '发票中奖（中）',
    effect: 'reward',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.28.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 29,
    summary: '发票中奖（大）',
    effect: 'reward',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.29.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 30,
    summary: '缴保险费',
    effect: 'fine',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.30.amountPI', { pi: true, unit: '元' })],
    notes: ['付款进公库，不是付给保险公司'],
  },
  {
    id: 31,
    summary: '领到保险金',
    effect: 'reward',
    target: '自己',
    feasible: '恒可',
    params: [p('amount', 'fate.31.amountPI', { pi: true, unit: '元' })],
  },
  {
    id: 32,
    summary: '卡片道具全换点券',
    effect: 'sellAllCardsTools',
    target: '自己',
    feasible: '恒可',
    params: [],
    notes: [
      '点券 += Σ 卡价 + Σ 道具价 × 数量（座驾先折回道具再卖），**全价**、不乘 0.9；engine.md §10.7「× 0.9」与 exe 不符（0.9 只用于商店卖回）',
      '劫难类加持只处理「逃过」',
    ],
  },
  {
    id: 33,
    summary: '闹事坐牢（短）',
    effect: 'jail',
    target: '自己（免罪 → 嫁祸后的最终目标）',
    feasible: 'v3.11 只在地图组标志 = 0 时（原版 4 张图）；v2.06 恒可',
    params: [p('days', 'fate.33.days', { unit: '天' })],
    notes: ['地图组 1..3 用表项 37..48 的文案变体（天数相同，见常量 fate.33.days1..3 等）'],
  },
  {
    id: 34,
    summary: '妨害风化坐牢',
    effect: 'jail',
    target: '自己（免罪 → 嫁祸后的最终目标）',
    feasible: '同 33',
    params: [p('days', 'fate.34.days', { unit: '天' })],
  },
  {
    id: 35,
    summary: '走私坐牢（长）',
    effect: 'jail',
    target: '自己（免罪 → 嫁祸后的最终目标）',
    feasible: '同 33',
    params: [p('days', 'fate.35.days', { unit: '天' })],
  },
  {
    id: 36,
    summary: '贩卖违禁品坐牢',
    effect: 'jail',
    target: '自己（免罪 → 嫁祸后的最终目标）',
    feasible: '同 33',
    params: [p('days', 'fate.36.days', { unit: '天' })],
  },
];

// ───────────────────────── 魔法屋 ─────────────────────────

export const MAGIC_CONDITION_SPEC: readonly EventSpec[] = [
  { id: 0, summary: '总资产最多者', effect: 'maxWealth', target: '并列全选；0 也参选', feasible: '', params: [] },
  {
    id: 1,
    summary: '地产块数最多者',
    effect: 'maxLots',
    target: '住宅 + 设施；并列全选；0 块不参选',
    feasible: '',
    params: [],
  },
  {
    id: 2,
    summary: '有建筑地产最多者',
    effect: 'maxBuilt',
    target: '等级 > 0 的住宅 + 设施；0 不参选',
    feasible: '',
    params: [],
  },
  { id: 3, summary: '现金最多者', effect: 'maxCash', target: '并列全选；0 不参选', feasible: '', params: [] },
  { id: 4, summary: '存款最多者', effect: 'maxDeposit', target: '并列全选；0 不参选', feasible: '', params: [] },
  { id: 5, summary: '点券最多者', effect: 'maxPoints', target: '并列全选；0 不参选', feasible: '', params: [] },
  { id: 6, summary: '步行的人', effect: 'walking', target: '座驾 & 3 = 0', feasible: '', params: [] },
  { id: 7, summary: '骑机车的人', effect: 'bike', target: '座驾 & 3 = 1', feasible: '', params: [] },
  { id: 8, summary: '开汽车的人', effect: 'car', target: '座驾 & 3 = 2', feasible: '', params: [] },
  { id: 9, summary: '有神明附身的人', effect: 'possessed', target: '附身神明字节 ≠ 0', feasible: '', params: [] },
  { id: 10, summary: '全部男性角色', effect: 'male', target: '性别字节 ≠ 0', feasible: '', params: [] },
  { id: 11, summary: '全部女性角色', effect: 'female', target: '性别字节 = 0', feasible: '', params: [] },
];

export const MAGIC_EFFECT_SPEC: readonly EventSpec[] = [
  {
    id: 0,
    summary: '卡片全卖换点券',
    effect: 'sellCards',
    target: '名单逐人',
    feasible: '',
    params: [],
    notes: ['全价计点券（同命运 32），不乘 0.9'],
  },
  { id: 1, summary: '连抽三张命运', effect: 'drawFate3', target: '名单逐人', feasible: '', params: [] },
  {
    id: 2,
    summary: '立即坐牢几天',
    effect: 'jail',
    target: '名单逐人（免罪 → 嫁祸后的最终目标）',
    feasible: '',
    params: [p('hate', 'magic.2.hatePI', { pi: true }), p('days', 'magic.2.jailDays', { unit: '天' })],
    notes: ['先记敌意（目标对施法者 + 90 × 物价指数），再过免罪 / 嫁祸判定'],
  },
  {
    id: 3,
    summary: '原地停一回合',
    effect: 'stay',
    target: '名单逐人',
    feasible: '',
    params: [],
    notes: ['停留计数 + 1'],
  },
  { id: 4, summary: '现金全部存入', effect: 'depositAll', target: '名单逐人', feasible: '', params: [] },
  {
    id: 5,
    summary: '脚下地产加盖一层',
    effect: 'upgradeHere',
    target: '名单中未受困、脚下是住宅或设施的人',
    feasible: '',
    params: [],
    notes: ['免费加 1 级'],
  },
  { id: 6, summary: '得到一张卡', effect: 'drawCard', target: '名单逐人', feasible: '', params: [] },
  { id: 7, summary: '原地向后转', effect: 'turnAround', target: '名单中未受困的人', feasible: '', params: [] },
  {
    id: 8,
    summary: '道具全卖换点券',
    effect: 'sellTools',
    target: '名单逐人',
    feasible: '',
    params: [],
    notes: ['座驾先折回道具再一起卖，全价'],
  },
  {
    id: 9,
    summary: '脚下地产拆一层',
    effect: 'demolishHere',
    target: '名单中未受困、脚下是住宅或设施的人',
    feasible: '',
    params: [],
    notes: ['地块损坏模式 0'],
  },
  {
    id: 10,
    summary: '住院检查几天',
    effect: 'hospital',
    target: '名单逐人（免罪 → 嫁祸后的最终目标）',
    feasible: '',
    params: [p('hate', 'magic.10.hatePI', { pi: true }), p('days', 'magic.10.hospitalDays', { unit: '天' })],
  },
  {
    id: 11,
    summary: '拍卖脚下地产',
    effect: 'auctionHere',
    target: '名单中未受困、脚下是住宅或设施的人',
    feasible: '',
    params: [],
    notes: ['拍卖函数的「卖方」参数传的是该目标玩家（V-R7「拍卖当格的钱归谁」：代码上归目标）'],
  },
];

/** 魔法屋流程的整体说明（与条件/效果无关的常量） */
export const MAGIC_FLOW_PARAMS: readonly ParamRef[] = [
  p('condPickHuman', 'magic.condPickHuman'),
  p('condPickAi', 'ai.magic.condPick'),
  p('aiSelfEffect', 'ai.magic.selfEffect'),
  p('aiEffectPick', 'ai.magic.effectPick'),
];

/** 辅助函数的 v3.11 调用点（用于在两版中识别处理函数调用了什么；迁移后读 call 目标） */
export const HELPER_CALL_SITES: Readonly<Record<string, string>> = {
  rand: '0x4491dd',
  fortune: '0x44c184',
  cardCheck: '0x44b352',
  jail: '0x44b362',
  hospital: '0x449285',
  away: '0x44c6e0',
  rangeDamage: '0x44922d',
  lotDamage: '0x44944f',
  auction: '0x4498a1',
  pay: '0x449ddb',
  give: '0x449a5c',
  addHate: '0x431e45',
  fateDraw: '0x431dbc',
  insurance: '0x44c218',
  stockRecalc: '0x44b04b',
  stockTrade: '0x44c8fd',
  sellCards: '0x431d35',
  sellTools: '0x43224f',
  cardCount: '0x44bc73',
  takeRandomCard: '0x44c46e',
  giveCard: '0x44c47e',
  drawCard: '0x4320ee',
  upgradeLot: '0x432059',
  turnAround: '0x4321d0',
  wreckVehicle: '0x44cd55',
  setLoanDue: '0x44c201',
};
